# -*- coding: utf-8 -*-
"""Aula 1 - Introdução à Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UcTUHTwhBO93RlV1TnV9swC3BKWYtEVu

Str
"""

nome = 'Wilber Godoy'

nome = "Thomas Santos"

print(nome)

"""Int"""

age = 14

nova_idade = 24

print(age + nova_idade)

"""Float"""

peso = 78.7

novo_peso = 92.3

print(peso + novo_peso)

"""Bool"""

texto = True

texto = False

print('O meu peso é '+str(age))

str(age)

x = int("32")

y = int("55")

print(x+y)

z = "67"

float(z)

print('A minha idade é', age)

print('A minha idade é {}'.format(age))

print(f'A minha idade é {nova_idade}')

"""Tuple"""

lista_de_tarefas = ("Dar aula", "Trabalhar", "Estudar", "Brincar")

print(lista_de_tarefas)

lista_de_tarefas[-2]

len(lista_de_tarefas)

len(f'A minha idade é {nova_idade}')

x = int(input("Insira o valor de x: "))

print(x)

y = int(input("Insira o valor de y: "))

print(x+y)

type(y)

lista_de_tarefas = ("Dar aula", "Trabalhar", "Estudar", "Brincar")

if "Ouvir música" in lista_de_tarefas:
  print('De fato, a tarefa Estudar está dentro de lista_de_tarefas!')
else: 
  print('Essa tarefa ainda não está inclusa!')

maioridade = 21

idade_intermediaria = 16

idade_real = 15

# Validação de idade maior que 18 anos
if idade_real >= 18:
  # print do usuário
  print('O usuário é MAIOR de idade')
elif idade_real >= 16 and idade_real < 18:
  #print("Já é QUASE maior de idade") # novo print para o usuario
  print(type(idade_real))
elif idade_real > 80:
  print('O usuário está beirando a 3ª idade')
else:
  print("O usuário é MENOR de idade")

''' Idade Real é
    Uma variavel que armazena
    A idade do usuário 
    Que irá usar o programa'''
""" asiuhaiufaui """

idade_real == 15

idade_real != 15

