# -*- coding: utf-8 -*-
"""Aula 7 - RegEx e APIs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ps4X67KUf35QAM0RUVnT9wXwR0zqJaEn
"""

import re

tel_regex = re.compile(r'\(\d\d\) \d\d\d\d\d\-\d\d\d\d')

coleta = tel_regex.search('Meu número é (41) 99123-4567 e meu nome é Josias!')

coleta.group()

coleta.group(0)

tel_regex_dois = re.compile('\(\d{2}\) \d{4,5}\-\d{4}')

coleta = tel_regex_dois.search('Meu número é (41) 99123-4567 e meu nome é Josias!')

coleta.group()

coleta = tel_regex_dois.search('Meu número é (41) 3123-4567 e meu nome é Josias!')

coleta.group()

tel_grupos = re.compile(r'(\d{2}) (\d{4,5})\-(\d{4})')

coleta = tel_grupos.search('Meu número é 41 3123-4567 e meu nome é Josias!')

coleta.group()

coleta.group(1)

coleta.group(2)

coleta.group(3)

coleta.groups()

regex_ou = re.compile('Wilber|Thomas')

coleta = regex_ou.search('Olá, meu nome é Wilber')

coleta.group()

coleta = regex_ou.search('Olá, meu nome é Thomas')

coleta.group()

coleta = regex_ou.search('Olá, meu nome é Sauron')

coleta.group()

regex_ou = re.compile('Wil(ber|mar)')

coleta = regex_ou.search('Olá, meu nome é Wilber!')

coleta.group()

coleta = regex_ou.search('Olá, meu nome é Wilmar!')

coleta.group()

coleta = regex_ou.search('Olá, meu nome é WilWil!')

coleta.group()

regex_bat = re.compile('Bat(wo)?man')

coleta = regex_bat.search('As aventuras de Batman')

coleta.group()

coleta = regex_bat.search('As aventuras de Batwoman')

coleta.group()

regex_risada = re.compile('(HA)*')

coleta = regex_risada.search('HAHAHAHA! Foi uma excelente piada!')

coleta.group()

regex_risada = re.compile('(HA)+')

coleta = regex_risada.search('HAHAHAHA! Foi uma excelente piada!')

coleta.group()

tel_regex = re.compile(r'\(\d{2}\) \d{4,5}\-\d{4}')

coleta = tel_regex.findall('Meu número residencial é (41) 3123-4567 e meu número de celular é (41) 99123-4567')

coleta[1], coleta[0]

regex_inicio = re.compile('^Sabia')

coleta = regex_inicio.search('Sabia que o significado da vida, do universo e tudo mais é 42?')

coleta.group()

regex_inicio = re.compile('^vida')

coleta = regex_inicio.search('Sabia que o significado da vida, do universo e tudo mais é 42?')

coleta.group()

regex_fim = re.compile('\d{2}$')

coleta = regex_fim.search('O significado da vida, do universo e tudo mais é 42')

coleta.group()

coleta = regex_fim.search('O significado da vida, do universo e tudo mais é 42?')

coleta.group()

regex_coringa = re.compile('.at')

coleta = regex_coringa.findall('The cat with the hat hit a bat')

coleta

regex_tudo = re.compile('Primeiro nome: (.*) Segundo Nome: (.*)')

coleta = regex_tudo.search('Primeiro nome: Harry Segundo Nome: Potter')

coleta.group(1), coleta.group(2)

regex_case = re.compile('metallica', re.IGNORECASE)

coleta = regex_case.search('MetallicA é uma banda de muito sucesso!')

coleta.group()

regex_subst = re.compile('\d')

substituicao = regex_subst.sub('*', 'Meu número residencial é (41) 99123-4567 e meu número de celular é (41) 3123-4567')

substituicao

regex_subst = re.compile('\w')

substituicao = regex_subst.sub('*', 'Meu número residencial é (41) 99123-4567 e meu número de celular é (41) 3123-4567')

substituicao

regex_separador = re.compile('\s')

substituicao = regex_separador.split('METALLICA é uma banda de muito sucesso!')

substituicao

regex_separador = re.compile('\D{5}')

substituicao = regex_separador.split('METALLICA é uma banda de muito sucesso!')

substituicao

regex_cpf = re.compile('\d{3}\.?\d{3}\.?\d{3}\-?\d{2}')

coleta = regex_cpf.findall('O seu CPF é 470.485.110-95 e o meu é 11745629009, 123.456789-11')

coleta

regex_tel = re.compile('\(?\d{2}\)?\s?\d{4,5}\-?\d{4}')

coleta = regex_tel.findall('O seu telefone fixo é (41) 3123-4567, já o celular é 41 99123-4567 e o meu seria 4131234567.')

coleta

regex_email = re.compile('(?:\w+\.)*\w*\@\w*(?:\.\w+)+')

coleta = regex_email.findall('O seu e-mail é tiara.hessel9@yahoo.com, o meu e-mail é shaun_nitzsche96@hotmail.com e acredito que podemos criar um e-mail em conjunto chamado alphonso19@outlook.com.br.')

coleta

